#!/bin/bash

ip=$1

mmdb=$( mmdblookup -f /var/lib/GeoIP/GeoLite2-Country.mmdb -i $ip country )
rv=$?

if [ $rv != 0 ] || [ -z "$mmdb" ] ; then
	logger -t ip2country "Lookup of $ip with mmdb failed (error $rv). Retrying with freegeoip ..."
	#sleep 15
	country=$(wget -qO - https://freegeoip.app/csv/$ip | awk -F, '{print $2, $3}')
else
	country=$(echo "$mmdb" | perl -00 -nle '($iso)=/"iso_code":\s+"([^"]+)/; ($n)=/"en":\s+"(.*?)"/; print join(" ", $iso, $n);')
fi

[ -z "$country" ] && logger -t ip2country "Lookup of $ip failed again."

echo "$country"
